allowBuilds:
  esbuild: true
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false
  workerd: false
  prisma: true
  "@prisma/client": true
  "@prisma/engines": true
  "@node-rs/argon2": true
